### PR TITLE
Make sure hydrate is called within comparisons

### LINKED ISSUE #19: MaybeNumber's Coercion with Queries Returns Unexpected Results
@HTMLGhozt commented on [Wed Sep 19 2018](https://github.com/canjs/can-data-types/issues/7)

`MaybeNumber`'s coercion has unexpected results when comparing query to query.
```js
const queryLogic = new QueryLogic({
  identity: ["id"],
  keys: { age: MaybeNumber }
});
const unionized = queryLogic.union(
  {filter: {age: 7}},
  {filter: {age: "07"}}
);
console.log( unionized );
// expected:  {filter: {age: 7}}, received:  "{'filter':{'age':{'$in':[7,'07']}}}"
```
demo: https://codepen.io/TDillard/pen/MqZqzO

Similarly, `MaybeNumber` has unexpected results when comparing query to an instance.
- `queryLogic.filterMembers({filter: {age: 7}}, [{age: "07"}]);` returns `[{age: "07"}]`.
- `queryLogic.filterMembers({filter: {age: "07"}}, [{age: 7}])` returns an empty array.

### PR DESCRIPTION
**Pull request by justinbmeyer**
fixes #19 

comparisons are something like `{$gt: 5}`, those need to get converted to `new GreaterThan(5)`.  This happens in comparisons.hydrate().

```js
comparisons.hydrate({$gt: 5}, unknown) //-> new GreaterThan(5)
```

What's supposed to happen, is that the 5 can be converted to `new MaybeNumberSet(5)`. So something like this should happen:

```js
comparisons.hydrate({$gt: 5}, hydrateUnknownType) //-> new GreaterThan(new MaybeNumberSet(5))
```

the `hydrateUnknownType` is used to convert `5` to `new MaybeNumberSet(5)`.  It wasn't be called if hydrate was called like:

```js
comparisons.hydrate(5, hydrateUnknownType) //-> new In([new MaybeNumberSet(5)])
```

or

```js
comparisons.hydrate([5,6], hydrateUnknownType) //-> new In([new MaybeNumberSet(5), new MaybeNumberSet(6)])
```

### CODE REVIEW

File: src/serializers/comparisons.js [hunk 1]
```diff
@@ -54,68 +54,70 @@ addHydrateFromValues("$nin", makeNew(is.GreaterThan));
...
+				if(andClauses.length > 1) {
+					return new is.And(andClauses);
+				} else {
+					return andClauses[0];
+				}
+			} else {
+				return hydrateUnknown(value);
+			}
+		} else {
+			return new is.In([hydrateUnknown(value)]);
```
Comment (justinbmeyer) [inline src/serializers/comparisons.js]: Part of this actual fix

File: src/serializers/comparisons.js [hunk 2]
```diff
@@ -54,68 +54,70 @@ addHydrateFromValues("$nin", makeNew(is.GreaterThan));
...
+					var hydrator = hydrateMap[key];
+					return hydrator(part, hydrateUnknown);
+				});
+				if(andClauses.length > 1) {
+					return new is.And(andClauses);
+				} else {
+					return andClauses[0];
+				}
+			} else {
+				return hydrateUnknown(value);
```
Comment (justinbmeyer) [inline src/serializers/comparisons.js]: part of this actual fix
