### PR TITLE
Fix query sorting schema issue

### LINKED ISSUE #45: Missed schema on helper.index
if `prop` doesn't have `can.getSchema` symbol it throws an error in this line:
https://github.com/canjs/can-query-logic/blob/8e54e7c9a80e051120a1c4561153a0eb98f1df82/src/helpers.js#L87

The solution might be passing `schema` argument to `helpers.index`.
The use-case that causes this issue is `can-connect` tests on the `update` function.
in this line:
https://github.com/canjs/can-connect/blob/513064178e1b229349cc219949aa69380c871a52/real-time/real-time.js#L499

### PR DESCRIPTION
**Pull request by cherifGsoul**
This fixes sorting literal objects (without `can@getSchema` symbol) issue by:

- Adding the `schema` to the `Sort` constructor in the `src/types/basic-query.js`
- Passing a `schema` param to the `makeSort` function
- Create `DefaultSort` constructor with a default `schema`
- Passing the `schema` to `getIndex`, `getIdentityIndex` and `getIdentityIndexByDirection` in `src/helpers.js`.

Fixes #45

### CODE REVIEW

File: src/helpers-test.js [hunk 1]
```diff
@@ -85,3 +85,35 @@ QUnit.test(".getIndex should not sort unchanged items #33", function() {
...
+	var items = [
+		{id: 1, name: "Item 0"},
+		{id: 2, name: "Item 1"},
+		{id: 3, name: "Item 2"},
+		{id: 4, name: "Item 3"},
+		{id: 5, name: "Item 4"}
+	];
+
+	canReflect.eachIndex(items, function(item) {
+		canReflect.assignSymbols(item, {
```
Comment (justinbmeyer) [inline src/helpers-test.js]: the items should not have a schema right?

Comment (cherifGsoul) [reply src/helpers-test.js]: @justinbmeyer I updated the test!
